---
title: "Transparency in Scientific Literature"
author: "Garland Xie"
date: "22/09/2021"
output: pdf_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 1. The article

[@norton2019]

# The checklist

The journal of this chosen article does not any form of checklist with respect to transparency and reproducibility.

In that case, I will evaluate the article based on a previous checklist [@parker2018].

## Questions to promote transparent reporting of methods and results 

Q1. Were all sample sizes fully reported, including exact values for all subsets of data and for all statistical analyses?

A1. No, it's unclear what the exact sample sizes were for subsets of data.

Q2. Are the methods reported in sufficient detail to allow another researcher to gather the same data and run the identical analyses?

Q2. Yes.

Q3a. Are statistical results for each test reported in sufficient detail?

A3a: Yes.

Q3b. Are results from all variables and from all models reported?

A3b: Yes.

Q4. Were observers kept unaware of the experimental treatment imposed on the samples when recording observations or measurements so as to minimize unconscious bias?

A4: Yes.

## Questions to check biases of reviewers and authors 

Q5. Did the authors explain how sample size was decided, or when an experiment with pre-set sample sizes was terminated?

A5: Yes.

Q6. Did the authors develop their analysis plan, including choices of variables, without looking at the data, for instance prior to gathering data or with a dummy data set?

A6. No, the authors did not include a published pre-registered report associated with this article.

Q7. How suitable do you find the research methods without considering the outcome?

A7. The methods are suitable, independent from the results, as the authors conducted tests to determine the method's effectiveness (e.g., testing for multivariate homogeneity of variance for ordination techniques).

Q8. Are the sample sizes large enough to justify the authors' conclusions?

A8. Yes.

Q9. What does the size of the estimated effect suggest about its biological or practical importance, and what does uncertainty around that effect estimate suggest about the estimate's precision?

A9.

Q10. How unexpected would you judge these results to be in light of prior empirically derived understanding?

A10:

# References
